VKInfoSite/VKInfoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('vksearch.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

VKInfoSite/main/urls.py
# pylint: skip-file
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.login_page, name='login_page'),

    url(r'^settings/$', views.change_settings, name='change_settings'),
    url(r'^change_settings_result/$', views.change_settings_result, name='change_settings_result'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^add_user/result/$', views.add_user_result, name='add_user_result'),

    url(r'^user_info/$', views.user_info, name='user_info'),
    url(r'^user_info/show_info/$', views.get_user_info, name='get_user_info'),

    url(r'^user_changes/$', views.get_changes, name='get_changes'),
    url(r'^user_changes/get_dates/$', views.get_dates, name='get_dates'),
    url(r'^user_changes/show/$', views.get_user_changes, name='get_user_changes'),

    url(r'^users_relation/$', views.get_mutual_activity, name='get_mutual_activity'),
    url(r'^users_relation/get_dates/$', views.get_users_dates, name='get_users_dates'),
    url(r'^users_relation/show/$', views.get_relations, name='get_relations'),
]
#leaflet/folium instagram_scrapper

VKInfoSite/vksearch/urls.py
# pylint: skip-file
from django.conf.urls import url
from . import views

app_name = 'vksearch'

urlpatterns = [
    url(r'^search/$', views.get_search_params, name='get_search_params'),
    url(r'^search_result/$', views.SearchView.as_view(), name='get_search_result'),

    url(r'^add_filter/1/$', views.add_search_filter_1, name='add_search_filter_1'),
    url(r'^add_filter/2/$', views.add_search_filter_2, name='add_search_filter_2'),
    url(r'^add_filter/result/$', views.add_filter_result, name='add_filter_result'),

    url(r'^delete_filter/$', views.delete_filter, name='delete_filter'),
    url(r'^delete_filter/result/$', views.delete_filter_result, name='delete_filter_result'),
]

VKInfoSite/vksearch/views.py
# pylint: disable=unused-argument, no-self-use, too-many-locals, too-many-branches, too-many-statements
"""VK Search app backend"""
import ast
import json
import time
import vk
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from main import mongo
from main.decorators import unauthenticated_user, post_method, check_token
from .mongo import VKSearchFiltersStorage
from .vk_scripts import vk_api, VKSearchScripts


@unauthenticated_user
def get_search_params(request):
    """
    'search/' page view - displays page with search arguments
    """
    storage = VKSearchFiltersStorage.connect(db=mongo.get_conn())
    context = {
        'title': 'Search | VK Tracker',
        'filters': storage.get_all_philters_names()
    }
    return render(request, 'vksearch/searchPage.html', context)


class SearchView(View):
    """Search result page view"""

    template_name = 'vksearch/searchResultPage.html'
    title = 'Search results | VK Tracker'
    search_by_groups_cities_universities = VKSearchScripts.by_groups_cities_universities
    search_by_cities_universities = VKSearchScripts.by_cities_universities
    search_by_cities = VKSearchScripts.by_cities
    search_by_universities = VKSearchScripts.by_universities
    search_by_groups_cities = VKSearchScripts.by_groups_cities
    search_by_groups_universities = VKSearchScripts.by_groups_universities
    search_by_groups = VKSearchScripts.by_groups
    search_by_friends = VKSearchScripts.by_friends
    relation_options = {
        1: 'not married',  # не женат/не замужем
        2: 'has boyfriend/girlfriend',  # есть друг/есть подруга',
        3: 'engaged',  # 'помолвлен/помолвлена',
        4: 'married',  # 'женат/замужем',
        5: 'it\'s complicated',  # 'всё сложно',
        6: 'actively looking',  # 'в активном поиске',
        7: 'in love',  # 'влюблён/влюблена',
        8: 'in a civil marriage',  # 'в гражданском браке',
        0: 'not indicated',  # 'не указано'
    }

    @staticmethod
    def parse_response(response):
        """
        Parse response dict with multiple
        search results into one dict

        :param response: dict with multiple search results
        :return: merged dict with all search results
        """
        result = {
            'count': 0,
            'items': []
        }
        for item in response:
            result['count'] += item['count']
            result['items'] += item['items']
        return result

    def get(self, request):
        """Get method - redirects ro '/search' page"""
        return redirect('/search')

    @method_decorator(check_token, unauthenticated_user)
    def post(self, request):
        """Post method - loads users and displays results"""
        if 'groups_selected' not in request.POST \
                and 'cities_selected' not in request.POST \
                and 'universities_selected' not in request.POST \
                and 'friends_selected' not in request.POST:
            context = {
                'title': 'Error | VK Tracker',
                'message_title': 'Error',
                'message': 'You must specify at least 1 search parameter'
            }
            return render(request, 'info.html', context)

        filter_name = request.POST['filter']
        count = 1000

        storage = VKSearchFiltersStorage.connect(db=mongo.get_conn())
        search_filter = storage.get_filter(filter_name)

        kwargs = {
            'q': '"' + request.POST['q'] + '"' if request.POST['q'] else '""',
            'sex': request.POST['sex'],
            'age_from': request.POST['age_from'],
            'age_to': request.POST['age_to'],
            'has_photo': 1 if 'has_photo' in request.POST else 0,
            'count': count,
            'country_id': search_filter['country_id']
        }

        cities_selected = request.POST.get('cities_selected')
        universities_selected = request.POST.get('universities_selected')
        groups_selected = request.POST.get('groups_selected')
        friends_selected = request.POST.get('friends_selected')

        if cities_selected:
            kwargs['cities'] = search_filter['cities_titles']
        if universities_selected:
            kwargs['universities'] = search_filter['universities']
        if groups_selected:
            kwargs['groups'] = search_filter['groups']

        result = []
        if groups_selected and cities_selected and universities_selected:
            response = []
            kwargs.pop('groups')
            for group_id in search_filter['groups']:
                kwargs['group_id'] = group_id
                code = self.search_by_groups_cities_universities.format(**kwargs)
                response += vk_api(request, 'execute', code=code)
                time.sleep(0.34)
            result.append(SearchView.parse_response(response))
        else:
            if groups_selected and cities_selected and not universities_selected:
                code = self.search_by_groups_cities.format(**kwargs)

            if groups_selected and universities_selected and not cities_selected:
                code = self.search_by_groups_universities.format(**kwargs)

            if cities_selected and universities_selected and not groups_selected:
                code = self.search_by_cities_universities.format(**kwargs)

            if groups_selected and not cities_selected and not universities_selected:
                code = self.search_by_groups.format(**kwargs)

            if cities_selected and not groups_selected and not universities_selected:
                code = self.search_by_cities.format(**kwargs)

            if universities_selected and not groups_selected and not cities_selected:
                code = self.search_by_universities.format(**kwargs)

            if groups_selected or cities_selected or universities_selected:
                response = vk_api(request, 'execute', code=code)
                time.sleep(0.34)
                result.append(SearchView.parse_response(response))

        if friends_selected:
            code = self.search_by_friends.format(friends=search_filter['friends'])
            result += vk_api(request, 'execute', code=code)

        result_ids = []
        for search_res in result:
            ids = {person['id'] for person in search_res['items']}
            result_ids.append(ids)

        if not result_ids:
            context = {
                'title': 'Error | VK Tracker',
                'message_title': 'Error',
                'message': '0 persons were found.'
            }
            return render(request, 'info.html', context)

        unique_ids = result_ids[0].copy()
        for ids in result_ids:
            unique_ids &= ids

        persons = []
        for search_res in result:
            for person in search_res['items']:
                fullname = person['first_name'] + ' ' + person['last_name']
                if person['id'] in unique_ids and kwargs['q'][1:-1] in fullname:
                    if person['sex'] == int(kwargs['sex']) or int(kwargs['sex']) == 0:
                        if 'relation' in person:
                            person['relation'] = self.relation_options[person['relation']]
                        else:
                            person['relation'] = self.relation_options[0]
                        persons.append(person)
                        unique_ids.remove(person['id'])
        context = {
            'title': self.title,
            'count': len(persons),
            'persons': persons,
        }
        return render(request, self.template_name, context)


@check_token
@unauthenticated_user
def add_search_filter_1(request):
    """
    'add_filter/1/' page view - displays page with params of new search filter:
     - Country
     - Cities
     - Universities parameters
    """
    kwargs = {
        'need_all': 1,
        'count': 1000
    }
    countries = vk_api(request, 'database.getCountries', **kwargs)
    context = {
        'title': 'Add search filter | VK Tracker',
        'countries': [item for item in countries['items'] if item['id'] < 5]
    }
    return render(request, 'vksearch/addFilter1.html', context)


@post_method
@unauthenticated_user
def add_search_filter_2(request):
    """
    'add_filter/2/' page view - displays page with params of new search filter:
     - Filter name
     - Universities names
     - Friends
     - Groups
    """
    country_id = request.POST['country_id']
    cities_ids, un_cities_ids, cities_titles = [], [], []
    for key in request.POST:
        if key.startswith('city'):
            req = vk_api(request,
                         method='database.getCities',
                         q=request.POST[key],
                         country_id=country_id)
            if req['count'] == 0:
                country = vk_api(request,
                                 method='database.getCountriesById',
                                 country_ids=country_id)[0]['title']
                context = {
                    'title': 'Error | VK Tracker',
                    'message_title': 'Error',
                    'message': "City '%s' not found in %s." % (request.POST[key], country)
                }
                return render(request, 'info.html', context)
            cities_ids.append(req['items'][0]['id'])
            cities_titles.append(request.POST[key])
        if key.startswith('un_city'):
            req = vk_api(request,
                         method='database.getCities',
                         q=request.POST[key],
                         country_id=country_id)
            if req['count'] == 0:
                country = vk_api(request,
                                 method='database.getCountriesById',
                                 country_ids=country_id)[0]['title']
                context = {
                    'title': 'Error | VK Tracker',
                    'message_title': 'Error',

VKInfoSite/templates/vksearch/addFilter1.html
{% extends "wrapper.html" %}

{% block content %}

{% load static %}

<div class="jumbotron">
    <h2>Add new filter (1/2)</h2>
    <form action="{% url 'vksearch:add_search_filter_2' %}" method="post">
        {% csrf_token %}
        <h4>Country</h4>
        <div class="form-group">    
            Select country:
            <select name="country_id" required>
            {% for country in countries %}
                <option value="{{ country.id }}">{{ country.title }}</option>
            {% endfor %}
            </select>
        </div>
        <h4>Cities</h4>
        <div class="form-group">
            Cities number:
            <input type="number" id="cities_num" value="0" size="2" min="0" max="5" style="width:50px" required>
        </div>
        <div id="cities" class="form-group"></div>
        <h4>Universities parameters</h4>
        <div class="form-group">
            University cities number:
            <input type="number" id="un_cities_num" value="0" size="2" min="0" max="5" style="width:50px" required>
        </div>
        <div id="un_cities" class="form-group"></div>
        <div class="form-group">
            Universities filter:
            <input type="text" name="universities_filter" id="universities_filter">
            <small class="text-muted">
              To search for multiple values, enter them separated by commas. Example: МГУ,МГТУ Баумана,РАНХиГС
            </small>
        </div>
        <input type="submit" class="btn btn-dark" value="Next">
    </form>
</div>

<script src="{% static 'vksearch/js/addFilterFirstPage.js' %}"></script>
<script type="text/javascript">
    main();
</script>

{% endblock %}

VKInfoSite/templates/vksearch/addFilter2.html
{% extends "wrapper.html" %}

{% block content %}

{% load static %}

<div class="jumbotron">
    <h2>Add new filter (2/2)</h2>
    <form action="{% url 'vksearch:add_filter_result' %}" method="post">
        {% csrf_token %}
        <h4>Filter name</h4>
        <div class="form-group">
            Name:
            <input type="text" id="filter_name" name="filter_name" required>
        </div>
        {% if universities %}
            <h4>Universities</h4>
            <div class="form-group">
                Universities number:
                <input type="number" id="universities_num" value="0" size="2" min="0" max="5" style="width:50px" required>
                <div id="universities_container" class="form-group"></div>
            </div>
        {% endif %}
        <h4>Friends</h4>
        <div class="form-group">
            Friends number:
            <input type="number" id="friends_num" value="0" size="2" min="0" max="5" style="width:50px" required>
        </div>
        <div id="friends" class="form-group"></div>
        <h4>Groups</h4>
        <div class="form-group">
            Groups number:
            <input type="number" id="groups_num" value="0" size="2" min="0" max="5" style="width:50px" required>
        </div>
        <div id="groups" class="form-group"></div>
        <input type="submit" class="btn btn-dark" value="Next">
        <label for="country_id">
            <input type="hidden" id="country_id" name="country_id" value="{{ country_id }}">
        </label>    
        <label for="cities_ids">
            <input type="hidden" id="cities_ids" name="cities_ids" value="{{ cities_ids }}">
        </label>
        <label for="cities_titles">
            <input type="hidden" id="cities_titles" name="cities_titles" value="{{ cities_titles }}">
        </label>
        {% if not universities %}
            <input type="hidden" id="universities_num" value="0" size="2" min="0" max="5" style="width:50px" required>
        {% endif %}
    </form>
</div>

<script src="{% static 'vksearch/js/addFilterSecondPage.js' %}"></script>
<script type="text/javascript">
    var universities = JSON.parse('{{ universities }}'.replace(/&quot;/gi, '"'));
    var all_universities_count = universities.length;
    main();
</script>

{% endblock %}

VKInfoSite/templates/vksearch/deleteFilter.html
{% extends "wrapper.html" %}

{% block content %}
<div class="jumbotron">
    <h2>Delete filter</h2>
    <form action="{% url 'vksearch:delete_filter_result' %}" method="post">
        {% csrf_token %}
        Select filter to delete:
        <select name="filter" required>
            {% for filter in filters %}
                <option value="{{ filter }}">{{ filter }}</option>
            {% endfor %}
        </select><br> 
        <input type="submit" class="btn btn-dark" value="Delete">
    </form>
    <br/>
</div>
{% endblock %}

VKInfoSite/templates/vksearch/searchPage.html
{% extends "wrapper.html" %}

{% block content %}

<div class="jumbotron">

    <h2>Search</h2>

    <form action="{% url 'vksearch:get_search_result' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                
                <table>
                    <tr>
                        <td>Query string:</td>
                        <td>
                            <input type="text" class="form-control" id="q" name="q">
                        </td>
                    </tr>
                    <tr>
                        <td>Sex:</td>
                        <td>
                            <select required="required" id="sex" name="sex">
                                <option value="2" selected>Male</option>
                                <option value="1">Female</option>
                                <option value="0">Any</option>            
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Age:</td>
                        <td>
                            from <input type="number" name="age_from" id="age_from" value="18" size="2" min="18" max="100" style="width:60px" required>
                            to <input type="number" name="age_to" id="age_to" value="20" size="2" min="18" max="100" style="width:60px" required><br>
                        </td>
                    </tr>
                    <tr>
                        <td>Has photo:</td>
                        <td>    
                            <div class="custom-control custom-checkbox my-1 mr-sm-2">
                                <input type="checkbox" class="custom-control-input" id="has_photo" name="has_photo">
                                <label class="custom-control-label" for="has_photo"></label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Select filter:</td>
                        <td>
                            <select required="required" id="filter" name="filter" >
                            {% for filter in filters %}
                                <option value="{{ filter }}">{{ filter }}</option>
                            {% endfor %}
                            </select>
                        </td>
                    </tr>
                </table>

                <br>Search by the following filter settings:<br>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="cities_selected" name="cities_selected">
                    <label class="custom-control-label" for="cities_selected">Cities</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="universities_selected" name="universities_selected">
                    <label class="custom-control-label" for="universities_selected">Universities</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="friends_selected" name="friends_selected">
                    <label class="custom-control-label" for="friends_selected">Friends</label>
                </div>
                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                    <input type="checkbox" class="custom-control-input" id="groups_selected" name="groups_selected">
                    <label class="custom-control-label" for="groups_selected">Groups</label>
                </div>

            </div>
        </div>

        <input type="submit" class="btn btn-dark" value="Search">
    </form>
    
</div>
{% endblock %}

VKInfoSite/templates/vksearch/searchResultPage.html
{% extends "wrapper.html" %}

{% block content %}

{% load static %}
{% load main_extras %}

<style type="text/css"> a { color: black; } img { cursor: pointer; }</style>
<script src="{% static 'main/js/main.js' %}"></script>

<div class="jumbotron">

    <h2>Search result: found {{ count }} persons</h2>
    <input class="form-control" type="text" placeholder="Search..." id="search-table" onkeyup='tableSearch("search-table", "table")'>
    <table id="table" class="table table-hover">
            <tr class="table-active">
                <th scope="col"><img height="20" src='{% sort_icon %}' onclick="sortTableByNums('table', 0, true)"></th>
                <th scope="col">Name <img height="20" src='{% sort_icon %}' onclick="sortTable('table', 1)"></th>
                <th scope="col">ID</th>
                <th scope="col">Domain <img height="20" src='{% sort_icon %}' onclick="sortTable('table', 2)"></th>
                <th scope="col">Relation <img height="20" src='{% sort_icon %}' onclick="sortTable('table', 3)"></th>
                <th scope="col">Is closed <img height="20" src='{% sort_icon %}' onclick="sortTable('table', 4)"></th>
                <th scope="col">Photo</th>
            </tr>
        </thead>
        <tbody>
            {% for person in persons %}
                    <tr>
                        <td scope="row"><strong>{{ forloop.counter }}</strong></td>
                        <td><a href="https://vk.com/id{{ person.id }}">{{ person.first_name }} {{ person.last_name }}</a></td>
                        <td>{{ person.id }}</td>
                        <td>{{ person.domain }}</td>
                        <td>{{ person.relation }}</td>
                        <td>{{ person.is_closed }}</td>
                        <td><img src={{ person.photo_400_orig }}></td>
                    </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}