VKInfoSite/VKInfoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('vksearch.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

VKInfoSite/main/urls.py
# pylint: skip-file
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.login_page, name='login_page'),

    url(r'^settings/$', views.change_settings, name='change_settings'),
    url(r'^change_settings_result/$', views.change_settings_result, name='change_settings_result'),

    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^add_user/result/$', views.add_user_result, name='add_user_result'),

    url(r'^user_info/$', views.user_info, name='user_info'),
    url(r'^user_info/show_info/$', views.get_user_info, name='get_user_info'),

    url(r'^user_changes/$', views.get_changes, name='get_changes'),
    url(r'^user_changes/get_dates/$', views.get_dates, name='get_dates'),
    url(r'^user_changes/show/$', views.get_user_changes, name='get_user_changes'),

    url(r'^users_relation/$', views.get_mutual_activity, name='get_mutual_activity'),
    url(r'^users_relation/get_dates/$', views.get_users_dates, name='get_users_dates'),
    url(r'^users_relation/show/$', views.get_relations, name='get_relations'),
]
#leaflet/folium instagram_scrapper

VKInfoSite/vksearch/urls.py
# pylint: skip-file
from django.conf.urls import url
from . import views

app_name = 'vksearch'

urlpatterns = [
    url(r'^search/$', views.get_search_params, name='get_search_params'),
    url(r'^search_result/$', views.SearchView.as_view(), name='get_search_result'),

    url(r'^add_filter/1/$', views.add_search_filter_1, name='add_search_filter_1'),
    url(r'^add_filter/2/$', views.add_search_filter_2, name='add_search_filter_2'),
    url(r'^add_filter/result/$', views.add_filter_result, name='add_filter_result'),

    url(r'^delete_filter/$', views.delete_filter, name='delete_filter'),
    url(r'^delete_filter/result/$', views.delete_filter_result, name='delete_filter_result'),
]

VKInfoSite/VKInfoSite/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Leadness, 2019-2020 -->
        <!-- https://github.com/LeadNess/VKUserInfo -->

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        {% load static %}
    	<link rel="stylesheet" href="{% static 'main/css/sidebar.css' %}">
    	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">

        <title>VKUserInfo</title>
    </head>
    <body class="sidebar-logo">
        <div class="row justify-content-center">
            <h1 style="color: white">VKUserInfo  </h1>
        </div>
        <main class="login-form">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">Login page</div>
                            {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                            {% endif %}
                            <div class="card-body">
                                <form action="{% url 'main:login_page' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label for="username" class="col-md-4 col-form-label text-md-right">Username</label>
                                        <div class="col-md-6">
                                            <input type="text" id="username" class="form-control" name="username" required autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                        <div class="col-md-6">
                                            <input type="password" id="password" class="form-control" name="password" required>
                                        </div>
                                    </div>

                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-dark">
                                            Login
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

    </body>
</html>

VKInfoSite/VKInfoSite/templates/wrapper.html
<!DOCTYPE html>
<html lang="en">
  <head>
  	
	<!-- Leadness, 2019-2020 -->
	<!-- https://github.com/LeadNess/VKUserInfo -->

  	<title>VKUserInfo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% load static %}
	<link rel="stylesheet" href="{% static 'main/css/sidebar.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
  </head>
  <body>
	<div class="sidebar-container">
	  <div class="sidebar-logo" href='/'>
	    VKUserInfo
	  </div>
	  <ul class="sidebar-navigation">
	  	<li class="header">User</li>
	  	<li>
	      <a href="#">
	        <i class="fa fa-tachometer" aria-hidden="true"></i> {{ user.username }}
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'main:login_page' %}">
	        <i class="fa fa-tachometer" aria-hidden="true"></i> Logout
	      </a>
	    </li>
	    <li class="header">Tracking</li>
	    <li>
	      <a href="{% url 'main:add_user' %}">
	        <i class="fa fa-home" aria-hidden="true"></i> Add user
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'main:user_info' %}">
	        <i class="fa fa-home" aria-hidden="true"></i> Get info
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'main:get_changes' %}">
	        <i class="fa fa-tachometer" aria-hidden="true"></i> Get changes
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'main:get_mutual_activity' %}">
	        <i class="fa fa-tachometer" aria-hidden="true"></i> Get mutual activity
	      </a>
	    </li>
	    <li class="header">Search</li>
	    <li>
	      <a href="{% url 'vksearch:get_search_params' %}">
	        <i class="fa fa-home" aria-hidden="true"></i> Search
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'vksearch:add_search_filter' %}">
	        <i class="fa fa-home" aria-hidden="true"></i> New search filter
	      </a>
	    </li>
	    <li>
	      <a href="{% url 'vksearch:delete_filter' %}">
	        <i class="fa fa-tachometer" aria-hidden="true"></i> Delete search filter
	      </a>
	    </li>
	    {% if request.user.is_superuser %}
		    <li class="header">Settings</li>
		    <li>
		      <a href="{% url 'main:change_settings' %}">
		        <i class="fa fa-home" aria-hidden="true"></i> Change
		      </a>
		    </li>
	    {% endif %}
	    <li class="header">Neo4j</li>
	    <li>
	      <a href="http://localhost:7474">
	        <i class="fa fa-home" aria-hidden="true"></i> Neo4j browser
	      </a>
	    </li>
	  </ul>
	</div>
	<div class="content-container">
	  <div class="container-fluid">
	  	<div class="jumbotron">
	  		{% block content %}
			{% endblock %}
	  	</div>
	  </div>
	</div>
  </body>
</html>